#!/bin/zsh
cd ~/nixos
nix flake update
sudo nixos-rebuild switch &>/tmp/nixos-switch.log || (
 cat /tmp/nixos-switch.log | rq --color always error && false)
gen=$(nixos-rebuild list-generations | grep current)
git commit -am "$gen"
git push
